openapi: 3.0.0
info:
  description: This API provides audit info
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: rtran21@my.bcit.ca

tags:
  - name: scanner
    description: records and scans the package being shipped
paths:
  /inventory/searchitem:
    get:
      tags:
        - fullfillment
      summary: searches inventory
      operationId: app.get_search_Inventory
      description: 
          Searches the inventory for the package
      parameters:
        - name: index
          in: query
          description: Gets the inventory at the index in the event store
          schema:
            type: integer
            example: 100
      responses: 
        '200': 
          description: Successfully returned a blood pressure event 
          content: 
            application/json: 
              schema: 
                type: object 
                items: 
                  $ref: '#/components/schemas/InventoryItem' 
        '400': 
          description: Invalid request 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string 
        '404': 
          description: Not Found 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string
  /fullfillment/shiporders:
    get:
      tags:
        - staff
      summary: track packages that need to be shipped and packages that are cancelled
      operationId: app.get_place_Shipment
      description: marks package for shipment
      parameters:
        - name: index
          in: query
          description: Gets the shipment at the index in the event storage
          schema:
            type: integer
            example: 100
      responses: 
        '200': 
          description: Successfully returned a blood pressure event 
          content: 
            application/json: 
              schema: 
                type: object 
                items: 
                  $ref: '#/components/schemas/shipping' 
        '400': 
          description: Invalid request 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string 
        '404': 
          description: Not Found 
          content: 
            application/json: 
              schema: 
                type: object 
                properties: 
                  message: 
                    type: string       
components:
  schemas:
    InventoryItem:
      type: object
      required:
        - device_id
        - trackingId
        - Itemname
        - manufacturer
        - quantity
        - weight
        - wishlisted
      properties:
        device_id:
          type: string
          example: A1B2C3D4
        trackingId:
          type: string
          format: uuid
          example: 1Z9999999999999999
        Itemname:
          type: string
          example: 'Fan'
        manufacturer:
          type: string
          example: 'Honeywell'
        quantity:
          type: integer
          example: 10
        weight:
          type: string
          example: '50 pounds'
        wishlisted:
          type: integer
          example: 50
    shipping:
      required:
        - device_id
        - shippingPriority
        - shippingCompany
        - address
        - name
        - deliveryDate
        - ordersreceived
      properties:
        device_id:
          type: string
          example: A1B2C3D4
        shippingPriority:
          type: string
          example: 'Standard'
        shippingCompany:
          type: string
          example: 'UPS'
        address:
          type: string
          example: '123 example Street'
        name:
          type: string
          example: 'John James'
        deliveryDate:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        ordersreceived:
          type: integer
          example: 50
