--- 
services: 
  db: 
    environment: 
      MYSQL_DATABASE: events
      MYSQL_PASSWORD: Password
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_USER: root
    expose: 
      - "3306"
    image: "mysql:5.7"
    ports: 
      - "3306:3306"
    restart: always
    volumes: 
      - "my-db:/var/lib/mysql"
  kafka: 
    command: 
      - start-kafka.sh
    depends_on: 
      - zookeeper
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: lab3855api.westus.cloudapp.azure.com
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka:29092,OUTSIDE://lab3855api.westus.cloudapp.azure.com:9092"
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: "INSIDE://:29092,OUTSIDE://:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    hostname: kafka
    image: wurstmeister/kafka
    ports: 
      - "9092:9092"
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
  zookeeper: 
    hostname: zookeeper
    image: wurstmeister/zookeeper
    ports: 
      - "2181"
version: "3.3"
volumes: 
  my-db: ~
